
dtw_mfcc_distance('samples/named/02-pullover-2.wav',...
                  'samples/named/02-pullover-3.wav',...
                  true)

dtw_mfcc_distance('samples/named/02-pullover-2.wav',...
                  'samples/named/04-blumentopf-3.wav',...
                  true)              
				  